name: Run tests on Simex Web Service
on:
  push:
    branches:
      - '*'
env:
  GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 21
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build and test
        shell: bash
        run: |
          echo "Running tests"
          sbt +test